apiVersion: v1
kind: Service
metadata:
  name: ds-external
spec:
  type: NodePort
  selector:
    app: ds
  ports:
    - name: ldap
      port: 1389
      targetPort: 1389
      nodePort: 31389
    - name: admin
      port: 4444
      targetPort: 4444
      nodePort: 31444