apiVersion: v1
kind: Service
metadata:
  name: ds
spec:
  clusterIP: None
  selector:
    app: ds1
  ports:
    - name: ldap
      port: 1389
    - name: ldaps
      port: 1636
    - name: admin
      port: 4444
    - name: replication
      port: 8989